EcommerceWithDjango/core/urls.py
from django.urls import path, include
from .views import (
    HomeView,
    CheckoutView,
    add_to_cart,
    OrderSummaryView,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    add_coupon,
    RequestRefund
)
from .views import ItemDetailView
app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home-page'),
    path('checkout/', CheckoutView, name='checkout'),
    path('payment/', PaymentView, name='payment'),
    path('orderSummary/', OrderSummaryView.as_view(), name='orderSummary'),
    path('products/<slug>/', ItemDetailView.as_view(), name='products'),
    path('add-to-cart/<slug>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item/<slug>', remove_single_item_from_cart,
         name='removing-single-item'),
    path('add_coupon/', add_coupon, name='add_coupon'),
    path('request-refund/', RequestRefund.as_view(), name='request-refund'),
]

EcommerceWithDjango/core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('s', 'Shirt'),
    ('sw', 'sportsWear'),
    ('ow', 'outWear'),
    ('bw', 'bottomwear')
)

LABEL_CHOICES = (
    ('p', 'primary'),
    ('s', 'secondary'),
    ('d', 'danger')
)

ADDRESS_CHOICES = (
    ('S', 'shipping'),
    ('B', 'billing'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    labels = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:products", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse('core:remove-from-cart', kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title} and {self.user.username}"

    def get_total_item_price(self):

        return self.quantity * self.item.price

    def get_total_discount_price(self):
        return self.quantity * (self.item.discount_price)

    def get_total_saving_price(self):
        return ((self.get_total_item_price()) - (self.get_total_discount_price()))

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_price()
        return self.get_total_item_price()


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    streetAddress = models.CharField(max_length=100)
    apartmentAddress = models.CharField(max_length=50)
    countries = CountryField(multiple=True, blank=True)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.streetAddress

    class Meta:
        verbose_name_plural = 'BillingAddresses'


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billling_address = models.ForeignKey(
        BillingAddress, related_name='billling_address', on_delete=models.SET_NULL, blank=True, null=True)
    shipping_address = models.ForeignKey(
        BillingAddress, related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        Coupon, on_delete=models.SET_NULL, null=True, blank=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    ref_code = models.CharField(max_length=30)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_items in self.items.all():
            total += order_items.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    amount = models.FloatField()

    def __str__(self):
        return self.user.username


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f'{self.pk}'

EcommerceWithDjango/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    
 
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="shortcut icon" href="#" />
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
</head>



<body style="background-color:rgb(18,18,18)">
    {% include "navbar.html" %}
    <div class="pt-4 mt-5">
        {% if messages %}

        {% for message in messages %}


        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        {% endfor %}

        {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}

</body>

</html>

EcommerceWithDjango/templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

  <!--Call to action-->

  <!--/.Call to action-->

  <hr class="my-4">

  <!-- Social icons -->
  <div class="pb-4">
    <a href="https://www.facebook.com/mdbootstrap" target="_blank">
      <i class="fab fa-facebook-f mr-3"></i>
    </a>

    <a href="https://twitter.com/MDBootstrap" target="_blank">
      <i class="fab fa-twitter mr-3"></i>
    </a>

    <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
      <i class="fab fa-youtube mr-3"></i>
    </a>

    <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
      <i class="fab fa-google-plus-g mr-3"></i>
    </a>

    <a href="https://dribbble.com/mdbootstrap" target="_blank">
      <i class="fab fa-dribbble mr-3"></i>
    </a>

    <a href="https://pinterest.com/mdbootstrap" target="_blank">
      <i class="fab fa-pinterest mr-3"></i>
    </a>

    <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
      <i class="fab fa-github mr-3"></i>
    </a>

    <a href="http://codepen.io/mdbootstrap/" target="_blank">
      <i class="fab fa-codepen mr-3"></i>
    </a>
  </div>
  <!-- Social icons -->

  <!--Copyright-->
  <div class="footer-copyright py-3">
    © 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
  </div>
  <!--/.Copyright-->

</footer>

EcommerceWithDjango/templates/home-page.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">


<style type="text/css">
  html,
  body,
  header,
  .carousel {
    height: 60vh;
  }

  @media (max-width: 740px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }

  @media (min-width: 800px) and (max-width: 850px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }
</style>


<body>

  <!-- Navbar -->

  <!-- Navbar -->

  <!--Carousel Wrapper-->

  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for item in items %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card" style="height: 400px;">

              <!--Card image-->
              <div class="view overlay">
                <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                  alt=""> -->
                <img src="{{ item.image.url }}" class="card-img-top" alt="image">
                <a href="{{item.get_absolute_url}}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{{ item.get_absolute_url }}" class="grey-text">
                  <h5>{{ item.get_category_display}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{item.get_labels_display}}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                    {% if item.discount_price %}
                    {{item.discount_price}}
                    {% else %}
                    {{ item.price }}
                    {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          {% endfor %}



        </div>
        <!--Fourth column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->

    <!--Grid row-->

    </section>


    <!--Section: Products v.3-->

    <!--Pagination-->
    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        <!--Arrow left-->
        {% if page_obj.has_previous %}
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}
        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    <!--Pagination-->
    {% endif %}
    </div>
  </main>
  <!--Main layout-->


  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>
{% endblock content %}

EcommerceWithDjango/templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="/" >
            <strong class="blue-text">Learning Django</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                <!-- <li class="nav-item active">
                    <a class="nav-link waves-effect" href="#">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/"
                        target="_blank">Checkout</a>
                </li> -->


            </ul>

            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'core:orderSummary' %}" class="nav-link waves-effect">
                        <span class="badge red z-depth-1 mr-1"> {{request.user|cart_item_count}} </span>
                        <i class="fas fa-shopping-cart"></i>
                        <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_logout' %}">

                        <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_login' %}">

                        <span class="clearfix d-none d-sm-inline-block"> Login </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'account_signup' %}">

                        <span class="clearfix d-none d-sm-inline-block"> Signup </span>
                    </a>
                </li>


                {% endif %}

            </ul>

        </div>

    </div>
</nav>

EcommerceWithDjango/templates/order_snippet.html
<h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
  </h4>

  <!-- Cart -->
  
  <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
        <h6 class="my-0">{{order_item.quantity}} x {{ order_item.item.title }}</h6>
        <small class="text-muted">Brief description</small>
      </div>
      <span class="text-muted">{{order_item.get_final_price}}</span>
    </li>
    {% endfor %}
    <li class="list-group-item d-flex justify-content-between bg-light">
      <div class="text-success">
        <h6 class="my-0">Use Below Promo code</h6>
        <small>{{ order.coupon.code }}</small>
      </div>
      <span class="text-success">-Rs{{order.coupon.amount}}</span>
    </li>
    <li class="list-group-item d-flex justify-content-between">
      <span>Total (Rs)</span>
      <strong>Rs{{order.get_total}}</strong>
    </li>
  </ul>


  <!-- promo code -->
  {% if DISPLAY_COUPON_FORM %}
  <form class="card p-2" method="POST" action="{% url 'core:add_coupon' %}">
    {% csrf_token %}
    <div class="input-group">
      <!-- <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username"
        aria-describedby="basic-addon2"> -->
        {{ couponform.code }}
      <div class="input-group-append">
        <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
      </div>
    </div>
  </form>
  {% endif %}

EcommerceWithDjango/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<main>
    <div class="container">
        <div class="table-responsive text-nowrap">

            <table class="table" >
              <thead>
                <tr>
                    <th style="color: white;" scope="col">#</th>
                  <th  style="color: white;" scope="col">Item Title</th>
                  <th style="color: white;" scope="col">Price</th>
                  <th style="color: white;" scope="col">Quantity</th>
                  <th style="color: white;" scope="col">Total Item Price</th>
                </tr>
              </thead>
              <tbody>
                  {% for order_item in object.items.all %}
                <tr>
                  <th style="color: white;" scope="row">{{forloop.counter}}</th>
                  <td style="color: white;">{{order_item.item.title}}</td>
                  <td style="color: white;">{{order_item.item.price}}</td>
                  <td style="color: white;"><a href="{%  url 'core:removing-single-item' order_item.item.slug %}"><i style="color: white;" class="fas fa-minus mr-2"></i></a>
                    {{order_item.quantity}} 
                    <a href="{%  url 'core:add-to-cart' order_item.item.slug %}"> <i style="color: white;" class="fas fa-plus ml-2"></i></a></td>
                  <td  style="color: white;">
                    {% if order_item.item.discount_price %}
                        ${{ order_item.get_total_discount_price }} <span class="badge badge-primary"> (Saving : {{order_item.get_total_saving_price}})</span>
                    {% else %}
                        ${{ order_item.get_total_item_price }}
                    {% endif %}
                  </td>
                  <td style="color: white;"><a href="{% url 'core:remove-from-cart' order_item.item.slug %}"><i style="color: white;" class="fas fa-trash-alt"></i></a></td>
                </tr>
                {% empty %}
                <tr>
                  <td style="color: white;" colspan="5" > Your cart is empty </td>
                  
                </tr>
                <tr>
                  <td colspan="5" >
                    <a class="btn btn-primary float-right" href="/">Continue Shopping</a> 
                  </td>
                </tr>
                {% endfor %}  
                
                {% if coupon.code %}
                <h4 style="color: white;">Coupon exists</h4>
                <tr>
                  <td style="color: white;" colspan="4" > Use coupon {{object.coupon.code}}</td>
                  <td style="color: white;"  >{{object.coupon.amount}}</td>
                </tr>
                {% endif %}

                {% if object.get_total %}
                <tr>
                  <td style="color: white;" colspan="4"><b> Order Total</b> </td>
                  <td style="color: white;">{{object.get_total}}</td>
                </tr>
                <tr>
                  <td colspan="4" > <a href="{% url 'core:checkout' %}" class="btn btn-warning float-right ml-2"> Proceed to Checkout </a>
                  <a class="btn btn-primary float-right" href="/">Continue Shopping</a> </td>
                  
                </tr>
                {% endif %}
              </tbody>
            </table>
          
          </div>
    </div>
</main>
{% endblock content %}

EcommerceWithDjango/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<body>



  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ object.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span>
                <span class="mr-1">
                  <del>{{object.price}}</del>
                </span>
                <span>${{object.discount_price}}</span> </span>
              {% else %}
              <span>

                <span>${{object.price}}</span> </span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{object.description}}</p>


            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url}}" class="btn btn-primary btn-md my-0 p">Remove from cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/"
        target="_blank" role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank"
        role="button">Start
        free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>
{% endblock content %}

EcommerceWithDjango/templates/refund-request.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2 style="color: white;">Request Refund</h2>
    <form style="color: white; " method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}